/**
 * WebDAV routes for FOC S3 Gateway.
 *
 * Runs on a dedicated Fastify instance on its own port.
 * Root (/) shows buckets as directories, /{bucket}/{key} maps to files.
 */

import { createHash } from 'node:crypto'
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify'
import type { Logger } from 'pino'
import type { MetadataStore } from '../storage/metadata-store.js'
import type { SynapseClient } from '../storage/synapse-client.js'
import type { DavResource } from './xml.js'
import { buildMultistatusXml } from './xml.js'

export interface WebDavRouteOptions {
  metadataStore: MetadataStore
  synapseClient: SynapseClient
  logger: Logger
}

/** Parse a path into bucket and key components */
function parseDavPath(url: string): { bucket?: string; key?: string } {
  let path = url.split('?')[0] ?? ''
  path = decodeURIComponent(path)
  // Remove leading slash
  if (path.startsWith('/')) path = path.slice(1)
  // Remove trailing slash
  if (path.endsWith('/')) path = path.slice(0, -1)

  if (!path) return {} // root

  const slashIdx = path.indexOf('/')
  if (slashIdx < 0) return { bucket: path } // bucket level
  return { bucket: path.slice(0, slashIdx), key: path.slice(slashIdx + 1) } // file level
}

/** Get Depth header (0, 1, or infinity) */
function getDepth(request: FastifyRequest): number {
  const depth = request.headers['depth']
  if (depth === '0') return 0
  if (depth === '1' || depth === undefined) return 1
  return Number.POSITIVE_INFINITY
}

export function registerWebDavRoutes(app: FastifyInstance, options: WebDavRouteOptions): void {
  const { metadataStore, synapseClient, logger } = options

  // ── OPTIONS ──────────────────────────────────────────────────────────
  app.options('/*', async (_request, reply) => {
    reply
      .status(200)
      .header('Allow', 'OPTIONS, GET, HEAD, PUT, DELETE, MKCOL, COPY, MOVE, PROPFIND')
      .header('DAV', '1')
      .header('Content-Length', '0')
      .send()
  })

  app.options('/', async (_request, reply) => {
    reply.status(200).header('Allow', 'OPTIONS, PROPFIND').header('DAV', '1').header('Content-Length', '0').send()
  })

  // ── PROPFIND ─────────────────────────────────────────────────────────
  app.route({
    method: 'PROPFIND',
    url: '/',
    handler: async (request, reply) => handlePropfind(request, reply, metadataStore, logger),
  })

  app.route({
    method: 'PROPFIND',
    url: '/*',
    handler: async (request, reply) => handlePropfind(request, reply, metadataStore, logger),
  })

  // ── GET (download) ───────────────────────────────────────────────────
  app.get('/*', async (request, reply) => {
    const { bucket, key } = parseDavPath(request.url)
    logger.debug({ bucket, key }, 'WebDAV GET')

    if (!bucket || !key) {
      reply.status(404).send('Not Found')
      return
    }

    if (!metadataStore.bucketExists(bucket)) {
      reply.status(404).send('Not Found')
      return
    }

    const obj = metadataStore.getObject(bucket, key)
    if (!obj) {
      reply.status(404).send('Not Found')
      return
    }

    try {
      const copies = metadataStore.getObjectCopies(bucket, key)
      const data = await synapseClient.download(obj.pieceCid, copies)

      reply
        .status(200)
        .header('Content-Type', obj.contentType)
        .header('Content-Length', data.length)
        .header('ETag', `"${obj.etag}"`)
        .header('Last-Modified', new Date(obj.lastModified).toUTCString())
        .send(Buffer.from(data))
    } catch (error) {
      logger.error({ error, bucket, key }, 'WebDAV download failed')
      reply.status(500).send('Internal Server Error')
    }
  })

  // Note: HEAD is auto-generated by Fastify from GET routes

  // ── PUT (upload) ─────────────────────────────────────────────────────
  app.put('/*', async (request, reply) => {
    const { bucket, key } = parseDavPath(request.url)
    logger.debug({ bucket, key }, 'WebDAV PUT')

    if (!bucket || !key) {
      reply.status(409).send('Cannot write to root or bucket level')
      return
    }

    if (!metadataStore.bucketExists(bucket)) {
      reply.status(409).send('Bucket does not exist')
      return
    }

    try {
      const contentLength = request.headers['content-length']
        ? Number.parseInt(request.headers['content-length'] as string, 10)
        : undefined
      const contentType = (request.headers['content-type'] as string | undefined) ?? 'application/octet-stream'

      // Validate size from Content-Length header (fast path)
      const MIN_UPLOAD_SIZE = 127
      const MAX_UPLOAD_SIZE = 1_065_353_216

      if (contentLength !== undefined) {
        if (contentLength === 0) {
          const etag = createHash('md5').update('').digest('hex')
          metadataStore.putObject(bucket, key, '', 0, contentType, etag)
          reply.status(201).header('ETag', `"${etag}"`).send()
          return
        }
        if (contentLength < MIN_UPLOAD_SIZE) {
          reply.status(400).send(`File too small: ${contentLength} bytes (minimum ${MIN_UPLOAD_SIZE} bytes)`)
          return
        }
        if (contentLength > MAX_UPLOAD_SIZE) {
          reply.status(413).send(`File too large: ${contentLength} bytes (maximum ~1 GiB)`)
          return
        }
      }

      // Stream upload: convert Node.js Readable to Web ReadableStream
      const md5 = createHash('md5')
      let totalBytes = 0

      const uploadStream = new ReadableStream<Uint8Array>({
        start(controller) {
          request.raw.on('data', (chunk: Buffer) => {
            const uint8 = new Uint8Array(chunk)
            md5.update(uint8)
            totalBytes += uint8.length
            controller.enqueue(uint8)
          })
          request.raw.on('end', () => {
            controller.close()
          })
          request.raw.on('error', (err) => {
            controller.error(err)
          })
        },
      })

      const result = await synapseClient.upload(uploadStream)
      const etag = md5.digest('hex')

      metadataStore.putObject(bucket, key, result.pieceCid, result.size, contentType, etag, result.copies)

      reply.status(201).header('ETag', `"${etag}"`).send()
    } catch (error) {
      logger.error({ error, bucket, key }, 'WebDAV upload failed')
      reply.status(500).send('Internal Server Error')
    }
  })

  // ── DELETE ───────────────────────────────────────────────────────────
  app.delete('/*', async (request, reply) => {
    const { bucket, key } = parseDavPath(request.url)
    logger.debug({ bucket, key }, 'WebDAV DELETE')

    if (!bucket) {
      reply.status(403).send('Cannot delete root')
      return
    }

    if (key) {
      if (!metadataStore.bucketExists(bucket)) {
        reply.status(404).send('Not Found')
        return
      }
      metadataStore.deleteObject(bucket, key)
      reply.status(204).send()
      return
    }

    if (!metadataStore.bucketExists(bucket)) {
      reply.status(404).send('Not Found')
      return
    }
    const deleted = metadataStore.deleteBucket(bucket)
    if (!deleted) {
      reply.status(409).send('Bucket not empty or is protected')
      return
    }
    reply.status(204).send()
  })

  // ── MKCOL (create bucket) ───────────────────────────────────────────
  app.route({
    method: 'MKCOL',
    url: '/*',
    handler: async (request: FastifyRequest, reply: FastifyReply) => {
      const { bucket, key } = parseDavPath(request.url)
      logger.debug({ bucket, key }, 'WebDAV MKCOL')

      if (!bucket) {
        reply.status(403).send('Cannot create root')
        return
      }

      if (key) {
        reply.status(201).send()
        return
      }

      const created = metadataStore.createBucket(bucket)
      if (!created) {
        reply.status(405).send('Bucket already exists')
        return
      }
      reply.status(201).send()
    },
  })

  // ── COPY ────────────────────────────────────────────────────────────
  app.route({
    method: 'COPY',
    url: '/*',
    handler: async (request: FastifyRequest, reply: FastifyReply) => {
      const { bucket: srcBucket, key: srcKey } = parseDavPath(request.url)
      const destination = request.headers['destination'] as string | undefined

      logger.debug({ srcBucket, srcKey, destination }, 'WebDAV COPY')

      if (!srcBucket || !srcKey || !destination) {
        reply.status(400).send('Bad Request')
        return
      }

      const destUrl = new URL(destination, `http://${request.headers.host}`)
      const { bucket: dstBucket, key: dstKey } = parseDavPath(destUrl.pathname)

      if (!dstBucket || !dstKey) {
        reply.status(400).send('Invalid destination')
        return
      }

      const copied = metadataStore.copyObject(srcBucket, srcKey, dstBucket, dstKey)
      if (!copied) {
        reply.status(404).send('Source not found')
        return
      }

      reply.status(201).send()
    },
  })

  // ── MOVE ────────────────────────────────────────────────────────────
  app.route({
    method: 'MOVE',
    url: '/*',
    handler: async (request: FastifyRequest, reply: FastifyReply) => {
      const { bucket: srcBucket, key: srcKey } = parseDavPath(request.url)
      const destination = request.headers['destination'] as string | undefined

      logger.debug({ srcBucket, srcKey, destination }, 'WebDAV MOVE')

      if (!srcBucket || !srcKey || !destination) {
        reply.status(400).send('Bad Request')
        return
      }

      const destUrl = new URL(destination, `http://${request.headers.host}`)
      const { bucket: dstBucket, key: dstKey } = parseDavPath(destUrl.pathname)

      if (!dstBucket || !dstKey) {
        reply.status(400).send('Invalid destination')
        return
      }

      const copied = metadataStore.copyObject(srcBucket, srcKey, dstBucket, dstKey)
      if (!copied) {
        reply.status(404).send('Source not found')
        return
      }

      metadataStore.deleteObject(srcBucket, srcKey)
      reply.status(201).send()
    },
  })

  // ── LOCK (stub) ─────────────────────────────────────────────────
  app.route({
    method: 'LOCK',
    url: '/*',
    handler: async (_request: FastifyRequest, reply: FastifyReply) => {
      const token = `opaquelocktoken:${Math.random().toString(36).substring(2)}`
      reply
        .status(200)
        .header('Lock-Token', `<${token}>`)
        .header('Content-Type', 'application/xml; charset=utf-8')
        .send(`<?xml version="1.0" encoding="UTF-8"?>
<D:prop xmlns:D="DAV:">
  <D:lockdiscovery>
    <D:activelock>
      <D:locktype><D:write/></D:locktype>
      <D:lockscope><D:exclusive/></D:lockscope>
      <D:depth>infinity</D:depth>
      <D:timeout>Second-3600</D:timeout>
      <D:locktoken><D:href>${token}</D:href></D:locktoken>
    </D:activelock>
  </D:lockdiscovery>
</D:prop>`)
    },
  })

  // ── UNLOCK (stub) ──────────────────────────────────────────────
  app.route({
    method: 'UNLOCK',
    url: '/*',
    handler: async (_request: FastifyRequest, reply: FastifyReply) => {
      reply.status(204).send()
    },
  })

  // ── PROPPATCH (stub) ──────────────────────────────────────────
  app.route({
    method: 'PROPPATCH',
    url: '/*',
    handler: async (request: FastifyRequest, reply: FastifyReply) => {
      const { bucket, key } = parseDavPath(request.url)
      const href = key ? `/${bucket}/${key}` : `/${bucket ?? ''}`

      reply
        .status(207)
        .header('Content-Type', 'application/xml; charset=utf-8')
        .send(`<?xml version="1.0" encoding="UTF-8"?>
<D:multistatus xmlns:D="DAV:">
  <D:response>
    <D:href>${href}</D:href>
    <D:propstat>
      <D:prop/>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
</D:multistatus>`)
    },
  })
}

// ── PROPFIND handler ───────────────────────────────────────────────────

async function handlePropfind(
  request: FastifyRequest,
  reply: FastifyReply,
  metadataStore: MetadataStore,
  logger: Logger
): Promise<void> {
  const { bucket, key } = parseDavPath(request.url)
  const depth = getDepth(request)

  logger.debug({ bucket, key, depth }, 'WebDAV PROPFIND')

  const resources: DavResource[] = []

  if (!bucket) {
    // Root: list buckets as collections
    resources.push({ href: '/', displayName: '', isCollection: true })

    if (depth > 0) {
      const buckets = metadataStore.listBuckets()
      for (const b of buckets) {
        resources.push({
          href: `/${b.name}/`,
          displayName: b.name,
          isCollection: true,
          lastModified: b.creationDate,
        })
      }
    }
  } else if (key) {
    // File or sub-directory level
    if (!metadataStore.bucketExists(bucket)) {
      reply.status(404).send('Not Found')
      return
    }

    const obj = metadataStore.getObject(bucket, key)
    if (obj) {
      resources.push({
        href: `/${bucket}/${key}`,
        displayName: key.split('/').pop() ?? key,
        isCollection: false,
        contentLength: obj.size,
        contentType: obj.contentType,
        lastModified: obj.lastModified,
        etag: obj.etag,
      })
    } else {
      const prefix = key.endsWith('/') ? key : `${key}/`
      const { objects, commonPrefixes } = metadataStore.listObjects(bucket, prefix, '/', 10000)

      if (objects.length === 0 && commonPrefixes.length === 0) {
        reply.status(404).send('Not Found')
        return
      }

      resources.push({
        href: `/${bucket}/${prefix}`,
        displayName: key.split('/').pop() ?? key,
        isCollection: true,
      })

      if (depth > 0) {
        for (const cp of commonPrefixes) {
          resources.push({
            href: `/${bucket}/${cp}`,
            displayName: cp.replace(/\/$/, '').split('/').pop() ?? cp,
            isCollection: true,
          })
        }
        for (const o of objects) {
          resources.push({
            href: `/${bucket}/${o.key}`,
            displayName: o.key.split('/').pop() ?? o.key,
            isCollection: false,
            contentLength: o.size,
            contentType: o.contentType,
            lastModified: o.lastModified,
            etag: o.etag,
          })
        }
      }
    }
  } else {
    // Bucket level
    if (!metadataStore.bucketExists(bucket)) {
      reply.status(404).send('Not Found')
      return
    }

    resources.push({ href: `/${bucket}/`, displayName: bucket, isCollection: true })

    if (depth > 0) {
      const { objects, commonPrefixes } = metadataStore.listObjects(bucket, '', '/', 10000)

      for (const prefix of commonPrefixes) {
        resources.push({
          href: `/${bucket}/${prefix}`,
          displayName: prefix.replace(/\/$/, '').split('/').pop() ?? prefix,
          isCollection: true,
        })
      }

      for (const obj of objects) {
        resources.push({
          href: `/${bucket}/${obj.key}`,
          displayName: obj.key.split('/').pop() ?? obj.key,
          isCollection: false,
          contentLength: obj.size,
          contentType: obj.contentType,
          lastModified: obj.lastModified,
          etag: obj.etag,
        })
      }
    }
  }

  const xml = buildMultistatusXml(resources)
  reply.status(207).header('Content-Type', 'application/xml; charset=utf-8').send(xml)
}
