import {
  type BlobFetcher,
  type CEKBytes,
  CoseAlgorithm,
  decrypt,
  decryptRange,
  deriveKey,
  type EnvelopeMetadata,
  encrypt,
  parseEnvelope,
} from 'foc-encryption'

/** Threshold in bytes above which chunked (seekable) encryption is used. */
const CHUNKED_THRESHOLD = 256 * 1024 // 256 KiB

export interface EncryptionMeta {
  algorithm: number
  envelopeSize: number
  chunkSize?: number | undefined
  chunkCount?: number | undefined
  encryptedSize: number
}

export interface EncryptionServiceOptions {
  secretKey: string
  salt?: Uint8Array
}

export class EncryptionService {
  private readonly secretKey: string
  private readonly providedSalt: Uint8Array | undefined
  private cek: CEKBytes | undefined
  private salt: Uint8Array | undefined

  constructor(options: EncryptionServiceOptions) {
    this.secretKey = options.secretKey
    this.providedSalt = options.salt
  }

  /**
   * Derives the CEK from the secret key via PBKDF2-SHA256 (600K iterations).
   * If a salt was provided in the constructor it is reused; otherwise a new
   * random salt is generated by `deriveKey`.
   */
  async init(): Promise<void> {
    const result = await deriveKey({ kind: 'password', password: this.secretKey }, this.providedSalt)
    this.cek = result.cek as CEKBytes
    this.salt = result.salt ?? this.providedSalt
  }

  /** Returns true once `init()` has completed successfully. */
  isReady(): boolean {
    return this.cek !== undefined
  }

  /**
   * Returns the PBKDF2 salt used during key derivation.
   * Persist this alongside the encrypted data so the same CEK can be
   * re-derived on restart.
   */
  getSalt(): Uint8Array {
    if (this.salt === undefined) {
      throw new Error('EncryptionService not initialised — call init() first')
    }
    return this.salt
  }

  private requireCek(): CEKBytes {
    if (this.cek === undefined) {
      throw new Error('EncryptionService not initialised — call init() first')
    }
    return this.cek
  }

  /**
   * Encrypts `plaintext` using the derived CEK.
   *
   * Algorithm selection:
   *  - > 256 KiB → CHUNKED_AES_256_GCM_STREAM (seekable)
   *  - ≤ 256 KiB → AES_256_GCM
   */
  async encryptBuffer(plaintext: Uint8Array): Promise<Uint8Array> {
    const cek = this.requireCek()
    if (plaintext.length > CHUNKED_THRESHOLD) {
      return encrypt(plaintext, cek, { algorithm: CoseAlgorithm.CHUNKED_AES_256_GCM_STREAM })
    }
    return encrypt(plaintext, cek, { algorithm: CoseAlgorithm.AES_256_GCM })
  }

  /** Decrypts an encrypted blob produced by `encryptBuffer`. */
  async decryptBuffer(blob: Uint8Array): Promise<Uint8Array> {
    return decrypt(blob, this.requireCek())
  }

  /** Sync overload: parse a fully-loaded encrypted blob. */
  parseEnvelope(blob: Uint8Array): EnvelopeMetadata
  /** Async overload: parse envelope headers via a BlobFetcher. */
  parseEnvelope(fetcher: BlobFetcher): Promise<EnvelopeMetadata>
  parseEnvelope(blobOrFetcher: Uint8Array | BlobFetcher): EnvelopeMetadata | Promise<EnvelopeMetadata> {
    if (blobOrFetcher instanceof Uint8Array) {
      return parseEnvelope(blobOrFetcher)
    }
    return parseEnvelope(blobOrFetcher)
  }

  /**
   * Decrypts a plaintext byte range without loading the full ciphertext.
   * Requires a seekable (chunked) envelope; throws SchemeNotSeekableError otherwise.
   */
  async decryptRange(
    fetcher: BlobFetcher,
    metadata: EnvelopeMetadata,
    range: { offset: number; length: number }
  ): Promise<Uint8Array> {
    return decryptRange(fetcher, metadata, this.requireCek(), range)
  }

  /**
   * Parses the envelope and returns metadata suitable for DB storage:
   * algorithm, envelope size, optional chunk info, and the total encrypted size.
   */
  async getEncryptionMeta(encryptedBlob: Uint8Array): Promise<EncryptionMeta> {
    const meta = parseEnvelope(encryptedBlob)
    return {
      algorithm: meta.algorithm,
      envelopeSize: meta.envelopeSize,
      chunkSize: meta.chunkSize,
      chunkCount: meta.chunkCount,
      encryptedSize: encryptedBlob.length,
    }
  }
}
